### ISSUE TITLE
Reviewed by Kent

### ISSUE THREAD

**Issue by kentcdodds** [tc39/proposal-class-fields#1]
Will close this when I've reviewed the proposal for stage-3

**Comment by kentcdodds** [comment]
Things look good to go from my point of view, assuming my assumptions are correct based on #2. cc @littledan :)

**Comment by nodkz** [comment]
Doble-underscore is better than #
And for stage-3 this proposal gathers just 3 github stars, too few likers. Looks like that 3 guys conspired in a bar 😕

**Comment by chicoxyzzy** [comment]
Double underscore is valid property identifier

**Comment by chicoxyzzy** [comment]
This proposal has 3 stars because it wasn't even publicly announced

**Comment by kentcdodds** [comment]
@littledan, I have another question. What would happen in this scenario?

```javascript
class Counter extends HTMLElement {
  #x = 0;

  #clicked() {
    #x++; // what error will the user see if this function is called out of context?
    window.requestAnimationFrame(this.render.bind(this));
  }

  constructor() {
    super();
    this.onclick = #clicked; // note the lack of binding here
  }

  connectedCallback() { this.render(); }

  render() {
    this.textContent = #x.toString();
  }
}
window.customElements.define('num-counter', Counter);
```

**Comment by littledan** [comment]
Not sure what you mean out of context. But say, from within Counter, you do `#clicked.call({})`, there are two possibilities for semantics:
- TypeError when #clicked is invoked, due to the method not existing on the receiver `{}`
- TypeError when #x is accessed from within #clicked (current spec text [here](https://littledan.github.io/proposal-class-fields/private-methods.html))

Clarifying this question will be one of the necessary steps to specifying private methods. I'm leaning towards the first option at this point (after previously specifying the other one), but I'd be interested in more input. cc @allenwb @bakkot .

**Comment by allenwb** [comment]
I recommend the second alternative as it is only private field access that have a hard branding requirement. Consider:

```js
class S {
   #helper() { //assume some sort of "private method" semantics
       this.bar();
    }
    foo() {return #helper.call(this)}
    bar() {Console.log("bar(S)")};
}
class Sub extends S {
    bar() {Console.log("bar(Sub)")}
}
new S().foo();  //logs: bar(S)
new Sub().foo(); //logs: bar(Sub)
```

There is no reason that #helper should do a brand test that requires its this value to be an instance of S. It has no dependency on the private field shape of its this value. The method as written can successfully operate on any object that has a `bar` method and with dynamically throw (can't call undefined) if applied to on object without a `bar` method.

A private method brand check makes private methods less useful and would add unnecessary extra mechanism and overhead.  As long as private field accesses are brand checked we should have to do any additional method level branding.

**Comment by kentcdodds** [comment]
Thanks, that sounds ok to me @allenwb. I expect that we'll need to have folks weigh before or at the next meeting though.

**Comment by littledan** [comment]
We'll have to discuss private methods in a separate topic; it's out of scope for this proposal. IMO both options are plausible choices.

**Comment by kentcdodds** [comment]
I'm good with that decision. The proposal looks good to me. Thanks!
