### ISSUE TITLE
Are private fields destructurable? [question]

### ISSUE THREAD

**Issue by mheiber** [tc39/proposal-class-fields#110]
Does this log `1`?

```js
class A {
    #x = 1;
    log () {
        const { #x: x } = this;
        console.log(x);
    }
}

new A().log()
```

**Comment by bakkot** [comment]
It doesn't currently parse, though [I think it would be a good idea to make it work as you expect](https://github.com/tc39/proposal-class-fields/issues/100#issuecomment-392092227) eventually.

**Comment by mheiber** [comment]
Thanks!
