### ISSUE TITLE
Make it explicit that PrivateName is a production in the lexical grammar

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-class-fields#127]
![screenshot 2018-09-10 16 16 56](https://user-images.githubusercontent.com/301201/45321995-f89fdd80-b514-11e8-84a4-8b19091fad8d.png)

This Updated Productions got me so long wondering where was the non-allowed-whitespace between the `#` and `IdentifierName` and I finally saw the subtle hint of `::` there and believe you're adding this very part - __PrivateName__ - to the Lexical Grammar, different from the previous 2 productions (FieldDefinition and ClassElementName).

It would be great if the proposal could be explicit about about this, rather than confusing. The produced material would also help justifying the tests being added to Test262. It's confusing to just guess one will just see the `::` in there and being explicit can't hurt anyone but provide useful clarification.

**Comment by littledan** [comment]
Yes, I see what you mean; that's pretty subtle. Do you think a separate subheading would be a good way to clarify this?
