### ISSUE TITLE
A "field" specifier for instance members?

### ISSUE THREAD

**Issue by JorisBlanken** [tc39/proposal-class-fields#130]
I can't help but feel that the currently proposed syntax look out of the ordinary.
Consider the following:
```javascript
class Example {
    x = 5;

    constructor(){
    }
}
```
Eventhough `x = 5;` is part of the class definition, it appears to belong to a piece of sequential(?) code.

Another issue with simply having `x = 5;` (without having a clear previous `let x;` or such) is that it appears too reminiscent of assignment to window/global, something that is considered bad behavior and is resented by many.

Would it be possible to require a new keyword such as `field` to be added infront of instance members?
Consider the following (imagine `field` to be treated by syntax highlighting as it would `static`):
```javascript
class Example {
    field x = 5;

    constructor(){
    }
}
```
I believe this would help make instance members appear more definition-like.

I also think this will help normalize the appearance of the # sigil use without having to add public/private specifiers.

**Comment by bakkot** [comment]
We discussed having different syntax for declarations (see e.g. [here](https://github.com/tc39/proposal-class-public-fields/issues/33) and [here](https://github.com/tc39/tc39-notes/blob/master/es8/2017-05/may-25.md#15iiib-updates-on-class-field-proposals-both-public-and-private)) and ultimately decided against it.

For me a fairly compelling argument was that many, many people are using this syntax through TypeScript and Babel without apparent confusion, so there doesn't seem to be an extremely strong need to be more explicit and verbose.
