### ISSUE TITLE
Typo in spec.html

### ISSUE THREAD

**Issue by ENvironmentSet** [tc39/proposal-class-fields#165]
[line 609](https://github.com/tc39/proposal-class-fields/blob/e516f197243fdda07942740d11a3d3b42f298d76/spec.html#L609)

even we uses `elements` instead of `methods` in `ClassDefinitionEvaluation`.
there is `methods` at line 609. this looks typo. 

we need `elements` instead of `methods` at this point. isn't it?

**Comment by littledan** [comment]
You're right, this should be `elements`. PRs welcome!
