### ISSUE TITLE
README.md has outdated multiple comma-separated definitions comment

### ISSUE THREAD

**Issue by tjcrowder** [tc39/proposal-class-fields#190]
README.md says:

> * Comma-separated multiple definitions: These are visible in the above example of class `C`, and are analogous to comma-separated definitions from var, let and const. They may be immediately useful when declaring multiple static fields, but later are useful in conjuction with decorators.

The class `C` in the README no longer has multiple comma-separated definitions as they were removed (#20). The README comment should be updated to reflect that.

**Comment by ljharb** [comment]
@littledan this can now be closed, by #191
