### ISSUE TITLE
How to add alias method in class? 

### ISSUE THREAD

**Issue by simonkcleung** [tc39/proposal-class-fields#279]
```
class A {
	a = 1;
	b(){console.log(this.a)};
}
```
How to do in `class` just same as `A.prototype.c=A.prototype.b;` ?

**Comment by ljharb** [comment]
You can’t do that exact thing inside the class body.

**Comment by MichaelTheriot** [comment]
I think it is unfortunate that in this scenario attempting `c = b` is actually legal and the mistake is only discovered later when the class is instantiated and throws a reference error.

**Comment by nicolo-ribaudo** [comment]
It's as much unfortunate as this code:
```js
class A {
  x = 2;
  getX() {
    return x; // Reference error
  }
}
```

People already know that they need `this` to access things of an object.

**Comment by MichaelTheriot** [comment]
That isn't quite the same though.

`x() { return 2; }` is only valid in a class or object declaration block. It is distinct, indicating separate rules apply.

`x = function ()  { return 2; };` is not distinct syntax and is used in general code blocks.

e.g.

```js
class A {
  x = function () { return 2; };
  y = x;
}

block: {
  x = function () { return 2; };
  y = x;
}
```

It is understood in `block` that `y` is equal to `x` at the end of execution. It is not unreasonable for developers to expect the same behavior from the same exact syntax in a class block.

It is unfortunate that due to the fact that `y = x` is not evaluated at class declaration execution, but later at instantiation, that the developer is not made aware of the error until it is too late.

**Comment by rdking** [comment]
@MichaelTheriot 
> It is not unreasonable for developers to expect the same behavior from the same exact syntax in a class block.

That was the underlying premise behind one of the [alternative proposals](https://github.com/rdking/proposal-class-members) I submitted a while back.

**Comment by littledan** [comment]
As clarified above, aliasing methods is simply not a goal of this proposal, so I'm closing this issue.

**Comment by trusktr** [comment]
@simonkcleung You can write:

```
class A {
	a = 1;
	b(){console.log(this.a)};
	c() { this.b() } // c is alias of b
}
```


@littledan What's not a goal, exactly?

I do think what @MichaelTheriot and @rdking are discussing is something valid to consider, but not sure it's exactly related to the OP.

**Comment by rdking** [comment]
Its not so much that aliasing methods needs to be a feature. It's just that given code like this:
```js
class Ex {
  x() {}
  y = this.x;
}
```
...and given the arguments made by TC39 members in other threads, the following statement is true:
* The declaration of `x` causes `this.x` to be immediately available as an RHS expression within the class lexical scope.

This means that regardless of what the value of `x` resolves to, it should be available to assign to y. This should be valid. If it is not, then there is yet another point of inconsistency in this proposal.

**Comment by simonkcleung** [comment]
@rdking 
```js
class Ex {
  x() {}
  y = this.x;
}
Here x is in the prototype object while y is not. What I want to do is both x and y are in the prototype and referencing same function.

**Comment by rdking** [comment]
@simonkcleung Sadly, that's one of the many costs of putting too much value on avoiding the prototype to avoid a 25% chance of foot-gun. Like @ljharb said, there's no solution to that. However, there is an ugly workaround.

```js
class Ex {
  x() {}
  y = (() => { return Ex.prototype.y = this.x; })()
}
```
You'll still be stuck with an instance property that you don't want, but you'll also have your prototype property.
