### ISSUE TITLE
Class field bug

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-class-fields#283]
![16dabe86f338b5e58dc9d41ffe84ed1](https://user-images.githubusercontent.com/24400797/71456609-35104f00-27d5-11ea-86de-e1d40cf28283.png)

**Comment by 1316346949** [comment]
![ee4697c954c3681738a321d09f49e6f](https://user-images.githubusercontent.com/24400797/71456619-3f324d80-27d5-11ea-974c-1d680570127a.png)

**Comment by 1316346949** [comment]
If you use the value of the value of #abc

**Comment by ljharb** [comment]
Because class fields use Define instead of Set, you’d have to do `this.a = 12345` in the constructor to trigger a superclass’ setter.
