### ISSUE TITLE
There is a problem with the [Set] and [Define ]

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-class-fields#287]
![shi111](https://user-images.githubusercontent.com/24400797/71616782-fa525080-2bf2-11ea-807a-2e8077e27eb5.png)

**Comment by 1316346949** [comment]
Setting a will be written to the log，because a was rewritten . we can know from the log that a has been rewritten，so we can find the problem.

**Comment by 1316346949** [comment]
But Define a cannot.

**Comment by 1316346949** [comment]
class A may have many fields, we can't understand how these fields are implemented

**Comment by 1316346949** [comment]
![image](https://user-images.githubusercontent.com/24400797/71617417-ebb96880-2bf5-11ea-8e8f-942c95e3121c.png)
According to the proposal-decorators hint, if we don't know how many fields there are in class A, we can only write this code to ensure that the logging function performs normally.

**Comment by 1316346949** [comment]
In most cases we don't know how many fields there are in class A. We can only write -> @set xxx = xxx

**Comment by 1316346949** [comment]
So in most cases, b will not be used, because we don't know how many fields the parent class has, and what these fields look like. We pretend to use b. There may be bugs without prompting. Can use "@set xxx = xxx or construtor" to ensure the program runs normally, or to understand the situation of all fields of the parent class

**Comment by 1316346949** [comment]
Sorry my english is not good, is there a clear description

**Comment by nicolo-ribaudo** [comment]
Please try to keep your description in a single comment. It's really hard to read through multiple "answers".

I don't understand how this issue is related to `[[Set]]` vs `[[Define]]`. Even with `[[Set]]`, the superclass won't log anything for `b =` and `c =`, because you didn't define setters for these functions.
