### ISSUE TITLE
Stage 4 (Question)

### ISSUE THREAD

**Issue by rolivo** [tc39/proposal-class-fields#303]
Is there a plan to move this proposal to stage 4 at the next meeting?

**Comment by ljharb** [comment]
No, because it's not on the [agenda](https://github.com/tc39/agendas/blob/master/2020/03.md), and the deadline for advancement has passed.

**Comment by jridgewell** [comment]
I think we're still waiting on complete implementations before this could qualify for advancement.

**Comment by littledan** [comment]
Thanks for accurately answering the question, @ljharb and @jridgewell .

**Comment by rolivo** [comment]
Thank you very much for the reply @ljharb  and @jridgewell.
