### ISSUE TITLE
grammar: private name access not allowed after a function call

### ISSUE THREAD

**Issue by claudepache** [tc39/proposal-class-fields#31]
The grammar allows `a.#p` or `a.b.#p`, but not `a(x).#p` or `a.b(x).c.#p`. I assume it is an oversight?

**Comment by spalger** [comment]
Pretty sure private field access needs to be statically identifiable, but the result of a function call is always dynamic.

**Comment by bakkot** [comment]
@spalger No, I think this should work, and is probably an oversight.

**Comment by littledan** [comment]
Seems like we're missing a production in *CallExpression* for private name access; is that what you're getting at?
