### ISSUE TITLE
private field and protected field

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-class-fields#311]
![image](https://user-images.githubusercontent.com/24400797/86867201-fe60ad00-c104-11ea-8b3f-11df5dc3b490.png)

**Comment by ljharb** [comment]
See #86 - the problem with protected fields has very little to do with syntax.

tl;dr: JS only has two kinds of "visibility": reachable and unreachable. The word "public" and "private" may suggest that it's the same as "access levels", but it's not.

**Comment by rdking** [comment]
@ljharb I know we've hashed this before, but I think I may have a different angle on the issue that may help you understand things a little differently than you do now. Hopefully it may convince you that "protected" is not something that must not enter the language.

Please humor me for a moment and define what you see as the difference between "reachability/visibility" and "access levels".
