### ISSUE TITLE
Private (#) vs Class#prototypeProperty

### ISSUE THREAD

**Issue by stevenvachon** [tc39/proposal-class-fields#34]
It causes confusion with things like `Array#includes` and `Array#length`.

**Comment by ljharb** [comment]
That's always been a documentation-only convention, borrowed largely from Ruby - indeed `a#b` has been conventionally short for `a.prototype.b`, but that's not a really good argument against all the reasons that class fields need to be own properties.

**Comment by stevenvachon** [comment]
Maybe we should use `$`, then. I still don't like not being able to use `private`, though.

**Comment by ljharb** [comment]
Neither of those are syntax; it has to be syntax to be hard-private. Give the [private fields FAQ](https://github.com/tc39/proposal-private-fields/blob/master/FAQ.md) a read.

**Comment by littledan** [comment]
Yes, this overlap is unfortunate, but I don't see a clear alternative.
