### ISSUE TITLE
Early Errors fix: ClassElementName instead of PropertyName

### ISSUE THREAD

**Issue by spectranaut** [tc39/proposal-class-fields#47]
In the first listed [Early Error](https://tc39.github.io/proposal-class-fields/#sec-static-semantics-early-errors) I believe there is a small mistake.

The original spec:
```
FieldDefinition :
    PropertyName Initializer
```

I believe this should be:
```
FieldDefinition :
    ClassElementName Initializer
```
As the `arguments` and `super()` ought to be forbidden from use in both private and public class field initializations?

**Comment by littledan** [comment]
Thanks for pointing out the error! I will apply your suggested fix.

Yes, they ought to be forbidden in both cases.
