### ISSUE TITLE
Adoption timeframe for major browsers?

### ISSUE THREAD

**Issue by kirkouimet** [tc39/proposal-class-fields#51]
I'm a huge fan of this proposal, makes for very clean class structures.

I've been watching for browsers to start adopting this feature behind a feature flag for a long time:

http://kangax.github.io/compat-table/esnext/

Currently no major browser has the feature implemented behind a flag. I'm currently using Babel to enable me to use the feature. I'm curious to know if anyone knows when Chrome and the others would start working on this one and how I can help.

**Comment by littledan** [comment]
The Kangax table will definitely be a trailing indicator here. From what I know of, there are implementations in progress in JSC and V8.
