### ISSUE TITLE
Initializers should be passed the instance (receiver) as |this|

### ISSUE THREAD

**Issue by kmiller68** [tc39/proposal-class-fields#9]
Currently, https://tc39.github.io/proposal-class-fields/#sec-define-field says:

DefineField(receiver, fieldRecord)
...
5. If initializer is not empty, then
    a. Let initValue be ? Call(initializer, undefined).

Why is the initializer not passed the receiver? I assume this is a bug since the DefineField operation takes one and does not use it.

**Comment by littledan** [comment]
Yes, that's definitely a bug! Pushed a fix. Thanks for noticing.
