### ISSUE TITLE
The '#' looks awful, please change it 

### ISSUE THREAD

**Issue by gynet** [tc39/proposal-class-fields#99]
The '#' looks really awful and even hard to read!

**Comment by gynet** [comment]
Not only best taste, I think many developers wont like writing such code
```JavaScript
 this.#x++;
```
Please justify or consider to chose something prefered by the community!

**Comment by jkrems** [comment]
> Please justify

There's a long FAQ that is justifying the choice in case you missed it: https://github.com/tc39/proposal-class-fields/blob/master/PRIVATE_SYNTAX_FAQ.md :)

**Comment by littledan** [comment]
Closing as a duplicate of several other issues.
